export const expectedSchema = {
  database_migrations: ['filename', 'checksum', 'applied_at'],
  accounts: [
    'id',
    'public_id',
    'email',
    'account_country',
    'status',
    'email_verified_at',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  credentials: [
    'id',
    'account_id',
    'type',
    'secret_hash',
    'hash_algorithm',
    'hash_version',
    'created_at',
    'updated_at',
    'revoked_at',
  ],
  sessions: [
    'id',
    'account_id',
    'family_id',
    'access_token_hash',
    'refresh_token_hash',
    'user_agent',
    'ip_address',
    'created_at',
    'last_seen_at',
    'expires_at',
    'revoked_at',
    'revoke_reason',
    'replaced_by_session_id',
    'access_expires_at',
  ],
  otps: [
    'id',
    'account_id',
    'destination',
    'purpose',
    'code_hash',
    'attempts',
    'max_attempts',
    'created_at',
    'expires_at',
    'verified_at',
    'consumed_at',
  ],
  security_events: [
    'id',
    'account_id',
    'event_type',
    'result',
    'ip_address',
    'user_agent',
    'request_id',
    'metadata',
    'occurred_at',
  ],
  markets: [
    'id',
    'code',
    'name',
    'status',
    'currency_code',
    'timezone',
    'default_locale',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  admin_users: [
    'id',
    'account_id',
    'display_name',
    'status',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  roles: [
    'id',
    'code',
    'name',
    'description',
    'is_system',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  permissions: ['id', 'code', 'description', 'created_at'],
  role_permissions: ['role_id', 'permission_id', 'created_at'],
  role_assignments: [
    'id',
    'admin_user_id',
    'role_id',
    'assigned_by_admin_user_id',
    'created_at',
    'revoked_at',
  ],
  market_access: [
    'id',
    'admin_user_id',
    'market_id',
    'granted_by_admin_user_id',
    'created_at',
    'revoked_at',
  ],
  audit_logs: [
    'id',
    'actor_type',
    'actor_id',
    'market_id',
    'action',
    'entity_type',
    'entity_id',
    'before',
    'after',
    'reason',
    'result',
    'request_id',
    'ip_address',
    'occurred_at',
  ],
  entity_timelines: [
    'id',
    'entity_type',
    'entity_id',
    'event_type',
    'actor_type',
    'actor_id',
    'market_id',
    'summary',
    'metadata',
    'occurred_at',
  ],
} as const;
