export const expectedSchema = {
  database_migrations: ['filename', 'checksum', 'applied_at'],
  accounts: [
    'id',
    'public_id',
    'email',
    'account_country',
    'status',
    'email_verified_at',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  credentials: [
    'id',
    'account_id',
    'type',
    'secret_hash',
    'hash_algorithm',
    'hash_version',
    'created_at',
    'updated_at',
    'revoked_at',
  ],
  sessions: [
    'id',
    'account_id',
    'family_id',
    'access_token_hash',
    'refresh_token_hash',
    'user_agent',
    'ip_address',
    'created_at',
    'last_seen_at',
    'expires_at',
    'revoked_at',
    'revoke_reason',
    'replaced_by_session_id',
    'access_expires_at',
  ],
  otps: [
    'id',
    'account_id',
    'destination',
    'purpose',
    'code_hash',
    'attempts',
    'max_attempts',
    'created_at',
    'expires_at',
    'verified_at',
    'consumed_at',
  ],
  security_events: [
    'id',
    'account_id',
    'event_type',
    'result',
    'ip_address',
    'user_agent',
    'request_id',
    'metadata',
    'occurred_at',
  ],
  markets: [
    'id',
    'code',
    'name',
    'status',
    'currency_code',
    'timezone',
    'default_locale',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  admin_users: [
    'id',
    'account_id',
    'display_name',
    'status',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  roles: [
    'id',
    'code',
    'name',
    'description',
    'is_system',
    'created_at',
    'updated_at',
    'archived_at',
  ],
  permissions: ['id', 'code', 'description', 'created_at'],
  role_permissions: ['role_id', 'permission_id', 'created_at'],
  role_assignments: [
    'id',
    'admin_user_id',
    'role_id',
    'assigned_by_admin_user_id',
    'created_at',
    'revoked_at',
  ],
  market_access: [
    'id',
    'admin_user_id',
    'market_id',
    'granted_by_admin_user_id',
    'created_at',
    'revoked_at',
  ],
  audit_logs: [
    'id',
    'actor_type',
    'actor_id',
    'market_id',
    'action',
    'entity_type',
    'entity_id',
    'before',
    'after',
    'reason',
    'result',
    'request_id',
    'ip_address',
    'occurred_at',
  ],
  entity_timelines: [
    'id',
    'entity_type',
    'entity_id',
    'event_type',
    'actor_type',
    'actor_id',
    'market_id',
    'summary',
    'metadata',
    'occurred_at',
  ],
  merchant_groups: [
    'id',
    'account_id',
    'market_id',
    'name',
    'created_at',
    'updated_at',
  ],
  merchant_account_access: [
    'id',
    'account_id',
    'merchant_group_id',
    'access_type',
    'created_at',
  ],
  merchant_branches: [
    'id',
    'merchant_group_id',
    'merchant_id',
    'market_id',
    'name',
    'status',
    'version',
    'created_at',
    'updated_at',
  ],
  merchant_profiles: [
    'id',
    'merchant_branch_id',
    'logo_url',
    'banner_url',
    'about_us',
    'address',
    'business_hours',
    'phone',
    'whatsapp',
    'website',
    'social_links',
    'created_at',
    'updated_at',
  ],
  merchant_api_idempotency_keys: [
    'id',
    'scope',
    'key',
    'request_hash',
    'response',
    'status_code',
    'created_at',
    'updated_at',
  ],
  merchant_profile_gallery_entries: [
    'id',
    'merchant_profile_id',
    'media_url',
    'position',
    'created_at',
  ],
  merchant_applications: [
    'id',
    'merchant_branch_id',
    'status',
    'version',
    'created_at',
    'updated_at',
  ],
  merchant_application_submissions: [
    'id',
    'merchant_application_id',
    'submission_version',
    'submitted_data',
    'submitted_at',
  ],
  merchant_application_reviews: [
    'id',
    'merchant_application_id',
    'reviewer_admin_user_id',
    'decision',
    'reason',
    'decided_at',
  ],
  merchant_kyc_submissions: [
    'id',
    'merchant_branch_id',
    'status',
    'submission_version',
    'submitted_data',
    'submitted_at',
  ],
  merchant_kyc_reviews: [
    'id',
    'merchant_kyc_submission_id',
    'reviewer_admin_user_id',
    'decision',
    'reason',
    'decided_at',
  ],
  merchant_documents: [
    'id',
    'merchant_branch_id',
    'document_type',
    'file_name',
    'mime_type',
    'file_size_bytes',
    'sha256_hash',
    'object_key',
    'uploaded_at',
  ],
  merchant_referrals: [
    'id',
    'merchant_branch_id',
    'referrer_account_id',
    'referred_at',
  ],
  merchant_terms_acceptances: [
    'id',
    'account_id',
    'merchant_branch_id',
    'terms_version',
    'accepted_at',
    'ip_address',
    'user_agent',
    'locale',
  ],
  merchant_status_history: [
    'id',
    'merchant_branch_id',
    'previous_status',
    'new_status',
    'changed_by_actor_type',
    'changed_by_actor_id',
    'reason',
    'changed_at',
  ],
  merchant_id_counters: ['market_id', 'channel', 'last_number'],
  service_fee_profiles: ['id', 'code', 'name', 'description', 'created_at'],
  service_fee_versions: [
    'id',
    'service_fee_profile_id',
    'rate',
    'effective_from',
    'effective_to',
    'status',
    'market_id',
    'created_at',
  ],
  special_percentages: [
    'id',
    'rate',
    'created_by_admin_user_id',
    'description',
    'market_id',
    'created_at',
  ],
  merchant_package_assignments: [
    'id',
    'merchant_branch_id',
    'service_fee_version_id',
    'special_percentage_id',
    'status',
    'is_default',
    'version',
    'created_at',
    'updated_at',
  ],
  mcp_accounts: [
    'id',
    'merchant_branch_id',
    'market_id',
    'available_balance',
    'total_balance',
    'version',
    'created_at',
    'updated_at',
  ],
  mcp_ledger_entries: [
    'id',
    'mcp_account_id',
    'sequence',
    'entry_type',
    'direction',
    'amount',
    'balance_delta',
    'available_delta',
    'source_type',
    'source_id',
    'idempotency_key',
    'payload_hash',
    'actor_type',
    'actor_id',
    'approval_request_id',
    'reversal_of_entry_id',
    'metadata',
    'effective_at',
    'created_at',
  ],
  mcp_recharge_requests: [
    'id',
    'mcp_account_id',
    'market_id',
    'requested_by_account_id',
    'amount',
    'channel',
    'status',
    'idempotency_key',
    'provider_event_id',
    'reviewed_by_admin_user_id',
    'review_reason',
    'ledger_entry_id',
    'created_at',
    'updated_at',
  ],
  mcp_refund_requests: [
    'id',
    'mcp_account_id',
    'market_id',
    'requested_by_account_id',
    'amount',
    'status',
    'reason',
    'idempotency_key',
    'reviewed_by_admin_user_id',
    'review_reason',
    'ledger_entry_id',
    'created_at',
    'updated_at',
  ],
  mcp_adjustment_requests: [
    'id',
    'mcp_account_id',
    'market_id',
    'maker_admin_user_id',
    'entry_type',
    'amount',
    'reason',
    'evidence',
    'status',
    'idempotency_key',
    'ledger_entry_id',
    'version',
    'created_at',
    'updated_at',
  ],
  mcp_adjustment_decisions: [
    'id',
    'adjustment_request_id',
    'market_id',
    'checker_admin_user_id',
    'decision',
    'reason',
    'decided_at',
  ],
} as const;
